BUTTONINFOACOUNT =                       "xpath=//span[@class='l-header__bottom-item-title has-arrow']"
ACOUNTINFO =                             "xpath=//a[@class='account__sidebar__nav__list__link__item sel-menu-info']"
PATHLOCATORINFOCONTA =                   "xpath=//h2[text()='Informações da conta']"
BUTTONPASSWORD =                         "xpath=//p[@class='accountStep3__row__link__text']"
CONFIRMPASSWORDPATH =                    "xpath=(//input[@class='checkout__forms__passForm__input'])[2]"
NEWPASSWORDPATH =                        "xpath=(//input[@class='checkout__forms__passForm__input'])[3]"
CONFIRMNEWPASSWORDPATH =                 "xpath=(//input[@class='checkout__forms__passForm__input'])[4]"
BUTTONCONFIRMPASSWORDCHANGE =            "xpath=(//button[@class='accountPopup__btn btn-primary'])[2]"
PATHMSGPASSWORDSUCCESS =                 "xpath=//div[text()='Senha editada com sucesso']"
PATHNAME =                               "xpath=//input[@class='checkout__forms__nameForm__input qa-accountInput__firstNameInput']"
LASTNAMEPATH =                           "xpath=//input[@class='checkout__forms__lastNameForm__input qa-accountInput__lastNameInput']"
BUTTONSALVAR =                           "xpath=//*[@id='content']/div[2]/main/div[2]/div[1]/div[2]/form/button"
MSGSUCESS =                              "Alterado com sucesso"
MSGSUCCESSPATH =                         "xpath=//div[text()='Alterado com sucesso']"
SAUDACAOSRA =                            "xpath=//*[@id='uniform-frau-input']"
SAUDACAOSR =                             "xpath=//*[@id='uniform-herr-input']/span"
MSGERROR_PATH =                          "//div[text()='Campo obrigatório']"
PATHMSGPASSWORDERRORATUAL =              "xpath=//div[text()='Senha atual não pode ser vazio.']"
PATHMSGPASSWORDERRORNOVA =               "xpath=//div[text()='Nova senha não pode ser vazio.']"
PATHMSGPASSWORDERRORCONFIRME =           "xpath=//div[text()='Confirme a nova senha não pode ser vazio.']"
WRONGPASSWORDMSG =                       "//div[text()='Senha incorreta.']"
MORETHAN50CARACTERESMSG =                "//div[text()='Máximo 50 caracteres']"
LESSTHAN06CARACTERESMSG =                "//div[text()='Min 6 caracteres']"
MSGSENHASNAOIGUAIS =                     "//div[text()='As senhas não estão iguais']"
SPACES =                                 "    "