HOMEBUTTONCART =                       "//span[@class='l-header__bottom-item-icon l-header__bottom-item-icon--cart']"
VALIDATECART =                         "//h2[@class='cart__heading']"
VALIDATECART_PRODUTO =                 "//p[text()='Produto']"
VALIDATECARTMEDIDA =                   "//p[text()='Medida']"
VALIDATECARTQUANTIDADE =               "//p[text()='Quantidade']"
VALIDATECARTPRECOTOTAL =               "//p[text()='Preço total']"
VALIDATECARTAPLICARVOUCHER =           "//a[@class='jsAddCoupon cartFormFooter__couponBoxLink']"
VALIDATECARTINFORMESEUCEP =            "//label[text()='Informe seu CEP:']"
VALIDATECARTVALORDOFRETE =             "//p[@class='cart__form__footer__deliverTextLeft']"
VALIDATECARTCALCULARFRETE =            "//p[text()='Calcular frete']"
VALIDATECARTVALORTOTAL =               "//p[text()='Valor total']"
VALIDATECARTCONTINUECOMPRANDO =        "//a[@class='cart__cartBox__text__link sel-continue-shopping jsBlockBackButton_cart']"
VALIDATECARTBTNCOMPRARCIMA =           "//button[@class='cart__cartBox__link btn-primary toCheckoutBtn sel-cart-checkout-button']"
VALIDATECARTBTNCOMPRARBAIXO =          "//p[@class='cart__cartBox__link__text']"
CLEARCART =                            "//span[@class='blockCartProduct__deleteText--remove']"
POPUPCLEARCART =                       "//div[@class='blockConfirmOverlay__content']"
BUTTONCONFIRMREMOVEFROMCART =          "//button[@class='blockConfirmOverlay__confirm jsBlockConfirmOverlay__confirm qaBlockConfirmOverlay__confirm']"
REMOVEFROMCARTMSG =                    "//div[@class='message__text']"
SELECTQUANTITY =                       "//a[@class='select2-choice']"
QUANTITY_2 =                           "(//li[@class='select2-results-dept-0 select2-result select2-result-selectable'])[2]"
QUANTITY_3 =                           "(//li[@class='select2-results-dept-0 select2-result select2-result-selectable'])[2]"
MSGSUCCESSUPDATECART =                 "//div[text()='Carrinho atualizado']"
VALIDATECARTEMPTY =                    "//p[text()='Seu carrinho está vazio!']"
ADDTOWISHLISTFROMCART =                "//p [@class='blockCartProduct__wishlist']"
POPUPWISHLISTCART =                    "//div[@class='blockAddToWishlistOverlay__content']"
BUTTONADDWISHLIST =                    "//button[@class='blockAddToWishlistOverlay__confirm qaBlockAddToWishlistOverlay__confirm btn-primary']"
MSGADDEDTOWISHLIST =                   "//div[@class='message__text']"
REMOVEFROMWISHLIST =                   "//button[@class='blockListProduct__delete qaBlockListProduct__delete']"
ENTERWISHLIST =                        "//span[@class='l-header__bottom-item-icon l-header__bottom-item-icon--wishlist']"
VALIDATEWISHLIST =                     "//p[@class='blockWishlistHeader__activeListName']"
MSGEMPTYWISHLIST =                     "//p[@class='wishlistNoProducts__text']"
VALIDATECHECKOUT =                     "//h2[text()='Escolher método de pagamento']"
BTNCHECKOUTBACKTOCART =                "//span[@class='checkoutHeader__backText']"
INPUTCEP =                              "//input[@class='inputPostCode']"
BTNCALCULARFRETE =                      "//button[@class='btn-primary btnCalculateFreight']"
VALIDATECEPSUCCESS =                    "(//p[@class='cart__form__footer__smallText'])[1]"
PRODUCTNAMEINCART =                     "//a[contains(@class,'blockCartProduct__nameLink')]"
VALIDATEPRODUCTNAME =                   "//h1[@class='blockProductHeading__heading']"
POSTCODEERROR =                         "//div[@class='postCodeError']"
VALIDATEPRICEPRODUCT1 =                 "(//p[@class='blockCartProduct__priceText'])[1]"
VALIDATEPRICEPRODUCT2 =                 "(//p[@class='blockCartProduct__priceText'])[2]"
ISNDD =                                 "//span[@class='icon-ndd blockSpecialCartNDD']"
NEWHERE =                               "//p[@class='blockRegisterPanel__headerText']"
BTNREGISTER_MODAL =                     "//button[contains(text(),'Cadastre-se gratuitamente')]"
BTNLOGIN_MODAL =                        "//button[contains(text(),'Login agora')] "
BTNCLOSE_MODAL =                        "//button[@class='wwOverlay__close loginAndRegisterOverlay__close wwOverlay__button--close qa-loginAndRegisterOverlay__close']"
BREADCRUMBSCHECKOUT =                   "//a[@class='checkout__breadcrumbs__link js-submitAddress']"
TITLELOGIN_CHECKOUT =                   "(//h2[@class='checkout__forms__header__heading'])[1]"
TITLEREGISTER_CHECKOUT =                "(//h2[@class='checkout__forms__header__heading'])[2]"
BTNLOGIN_CHECKOUT =                     "//button[@name='login']"
BTNREGISTER_CHECKOUT =                  "//button[@name='register']"
FIELD_DELIVERYVALUE =                   "//p[@class='cart__form__footer__deliverTextRight']"
FIELD_TOTALVALUE =                      "//p[@class='cart__form__footer__totalTextRight']"

