MY_ORDERS_BUTTON = "xpath=//a[@class='l-header__bottom-item-link']"
ORDERS_TABLE = "xpath=//div[@class='blockOrdersList ']"
ORDER_NUMBER_COLUMN = "xpath=//div[@class='blockOrdersCell blockOrdersCellHeader blockOrdersCell_number blockOrderInfo__item blockOrderInfo__item_withHeader blockOrderInfo__item_withHeader--OrderList']"
ORDER_STATUS_COLUMN = "xpath=//div[@class='blockOrdersCell blockOrdersCellHeader blockOrdersCell_status blockOrderInfo__item blockOrderInfo__item_withHeader blockOrderInfo__item_withHeader--OrderList']"
ORDER_DATE_COLUMN = "xpath=//div[@class='blockOrdersCell blockOrdersCellHeader blockOrdersCell_date blockOrderInfo__item blockOrderInfo__item_withHeader blockOrderInfo__item_withHeader--OrderList']"
ORDER_PRICE_COLUMN = "xpath=//div[@class='blockOrdersCell blockOrdersCellHeader blockOrdersCell_price blockOrderInfo__item blockOrderInfo__item_withHeader blockOrderInfo__item_withHeader--OrderList']"
ORDER_ACTION_COLUMN = "xpath=//div[@class='blockOrdersCell blockOrdersCellHeader blockOrdersCell_action blockOrderInfo__item blockOrderInfo__item_withHeader blockOrderInfo__item_withHeader--OrderList']"
ORDER_ELEMENT = "xpath=//div[@class='blockOrdersList__data ']"
MOST_RECENT_ORDER = "xpath=//a[@class='blockOrdersCell__text blockOrdersList__dataText blockOrdersCell__link blockOrdersCell__link_withAction']"
ORDER_TRACKING = "id:trackingMS-order"
CONTACT_BUTTON = "xpath=//a[@class='trackingMS-helperdeskLink']"
ORDER_RESUME = "xpath=//div[@class='trackingMS-order-resume']"
FAQ_ELEMENTS = "id:contactFaq"
CONTACT_CENTRAL = "id:contactAtendimento"
