FIRST_CATEGORIE_PRODUCT=    "xpath=(//span[@class='l-header__nav-tag'])[1]"
FIRST_PRODUCT_NAME=         "xpath=(//h2[@class='blockProduct__name blockProduct__headingTagProduct  qaBlockProduct__name'])[4]"
FIRST_PRODUCT_VALUE=        "xpath=(//span[@class='qaProductPrice blockProduct__priceAmount'])[1]"
INSIDE_NAME_PRODUCT=        "xpath=(//h1[@class='blockProductHeading__heading'])"
LINK_CALC_SHIPPING=         "xpath=(//a[@id='modal-postcode'])[1]"
TITLE_MODAL_CALC_CEP=       "xpath=(//span[@class='deliveryTimeSpan'])[1]"
INPUT_CALC_CEP=             "xpath=(//input[@id='calculateshipping-postcode'])"
BUTTON_CALC_CEP=            "xpath=(//button[@id='calculate-postcode'])"
TITLE_CAMPAING_PAGE=        "xpath=(//div[@class='item']//h1)"
MENSAGE_CEP_CONSULT=        "xpath=(//p[@class='paragraph-freight'])[1]"
CLOSE_MODAL_BUTTON=         "xpath=(//button[@class='wwOverlay__close popUpStoreOverlay__close wwOverlay__button--close qa-popUpStoreOverlay__close'])[2]"
NDD_ICON_CAR=               "xpath=(//span[@id='iconNDDProductDetail'])"
