ADD_PRODUCT_TO_CART_BUTTON = "xpath=//*[@id='buttonText']"
ACCESS_CART_BUTTON = "xpath=//span[@class='l-header__bottom-item-icon l-header__bottom-item-icon--cart']"
PROCEED_TO_CHECKOUT_BUTTON = "xpath=//button[@data-url='/checkout/index/']"
CHECKOUT_BUTTON_PIX = "xpath=//*[@id='uniform-pix']/span"
CONFIRM_PAYMENT_METHOD = "xpath=//span[text()='Continuar']"
ORDER_CONFIRMATION_TEXT = "Confirmar pedido"
CONFIRM_ORDER_BUTTON = "xpath=//button[@class='qa-checkout-submit-button checkoutBtn btn-primary js-submitFinish blockCheckoutHeading__button checkout__headingCTA']"
TEXT_PURCHASE_SUCCESS = "Você está a um passo de completar seu pedido"
SEARCH_BAR_INPUT = "xpath=//*[@id='searchInput']"
FIRST_SEARCH_RESULT = "(//div[@class='blockProductGrid__item qaBlockProductGrid__item '])[1]"
EDIT_SHIPPING_ADDRESS_BUTTON = "id:edit-shipping"
ADDRESS_FEMALE_USER_GENDER = "id:uniform-shipping-frau-input"
ADDRESS_FIRST_NAME = "id:shipping-name-input"
ADDRESS_LAST_NAME = "id:shipping-lastName-input"
ADDRESS_CEP = "id:shipping-code-input"
ADDRESS_NUMBER = "id:shipping-street_number-input"
ADDRESS_PHONE_NUMBER = "id:shipping-phone-input"
BILLING_ADDRESS_CPF = "id:billing-cpf-input"
BILLING_ADDRESS_CEP = "id:billing-code-input"
BILLING_ADDRESS_NUMBER = "id:billing-street_number-input"
BILLING_ADDRESS_PHONE = "id:billing-phone-input"
VALIDATE_PRODUCT_AT_CART = "//a[@class='l-header__bottom-cart-button btn-primary']"
