PRODUCTNAME =                  "xpath=(.//*[@class='blockProduct__name blockProduct__headingTagProduct  qaBlockProduct__name'])"
CATEGORY =                     "xpath=(.//span[@class='l-header__nav-tag'])"
WISHLISTICONINACTIVE =         "xpath=(.//*[@class='blockWishlistHeart__icon blockWishlistHeart__icon_pasive '])"
IMAGEPRODUCT =                 "xpath=(.//img[@class='blockListProduct__image'])"
PRODUCTPRICE =                 "xpath=(.//*[@class='blockListProduct__price'])"
PRODUCTSIZE =                  "xpath=(.//*[@class='blockListProduct__size'])"
BUTTONDELETEFROMWISHLIST =     "xpath=.//*[@class='blockListProduct__delete qaBlockListProduct__delete']"
WISHLISTNOPRODUCTSINFO =       "xpath=.//*[@class='wishlistNoProducts__info']"
SELECTWISHLIST =               "xpath=.//*[@class='blockAddToWishlistOverlay__headerText']"
ADDTOWISHLISTBUTTON =          "xpath=.//*[@class='blockAddToWishlistOverlay__confirm qaBlockAddToWishlistOverlay__confirm btn-primary']"
CLOSEADDWISHLIST =             "xpath=.//*[@class='blockAddToWishlistOverlay__close qaBlockAddToWishlistOverlay__close']"
WISHLISTBUTTON =               "xpath=.//*[@class='l-header__bottom-item-icon l-header__bottom-item-icon--wishlist']"
ADDWISHLISTBUTTON =            "xpath=.//*[@class='blockWishlistButton btn-default qa-addToWishlistBtn jsWishlistButton blockWishlistButton--active']"
NEWWISHLIST =                  "xpath=.//*[@class='blockAddToWishlistOverlay__addNewList qaBlockAddToWishlistOverlay__addNewList']"
NEWWISHLISTNAME =              "xpath=.//*[@class='blockAddToWishlistOverlay__input']"
ADDLISTBUTTON =                "xpath=.//*[@class='blockWishlistNavigation__addListButton qaBlockWishlistNavigation__addListButton']"
INPUTADDLISTBUTTONNAME =       "xpath=.//*[@class='blockCreateListOverlay__input']"
ADDBUTTON =                    "xpath=.//*[@class='btn-primary blockCreateListOverlay__confirm qaBlockCreateListOverlay__confirm']"
LOGINNOW =                     "xpath=.//*[@class='blockRegisterPanel__switchButton qa-blockRegisterPanel__switchButton']"
COOKIEPOLICYOVERLAY =          "xpath=.//*[@class='cookiePolicyOverlay__close']"
IDENTIFIERTEXTFIELDWISHLIST =  "name=LoginForm[email]"
PASSWORDTEXTFIELDWISHLIST =    "name=LoginForm[password]"
BUTTONLOGINWISHLIST =          "xpath=.//*[@class='newLogin blockLoginForm__submit qa-blockLoginForm__submit is-react']"
CHANGEWISHLIST =               "xpath=.//*[@class='blockActionMenu__icon blockActionMenu__icon_sort']"
MYWISHLIST =                   "xpath=.//*[@class='blockAddToWishlistOverlay__list qaBlockAddToWishlistOverlay__list1']"
PRODUCTNAMEWISHLIST =          "xpath=.//*[@class='blockListProduct__name']"
LISTNAME =                     "xpath=(.//*[@class='blockWishlistNavigation__listName'])"
EDITWISHLIST =                 "xpath=.//*[@class='wishlist__lists__action__addList qaWishlist__lists__action__addList btn-default']"
INPUTLISTNAME =                "xpath=.//*[@class='blockEditListOverlay__input']"
RENAMELIST =                   "xpath=.//*[@class='blockEditListOverlay__confirm qaBlockEditListOverlay__confirm btn-primary']"
DELETELIST =                   "xpath=.//*[@class='blockEditListOverlay__delete qaBlockEditListOverlay__delete btn-default']"
CONFIRMBUTTON =                "xpath=.//*[@class='blockConfirmOverlay__confirm jsBlockConfirmOverlay__confirm qaBlockConfirmOverlay__confirm']"
NEWCUSTOMWISHLIST =            "xpath=(.//*[@class='blockWishlistNavigation__listName'])[2]"
STANDARWISHLIST =              "xpath=(.//*[@class='blockWishlistNavigation__listName'])[1]"